import { createApp } from 'vue';
import App from './App.vue';
import './registerServiceWorker';
import router from './router';
import store from './store';
import VueAxios from 'vue-axios';
import axios from 'axios';
import './styles/tailwind.css';
import './styles/custom.css';
import VueSidebarMenu from 'vue-sidebar-menu';
import 'vue-sidebar-menu/dist/vue-sidebar-menu.css';
import { globalComponents } from './globalComponents';
import SmartTable from 'vuejs-smart-table';
import LitepieDatepicker from 'litepie-datepicker';
import { VueCollapsiblePanelGroup, VueCollapsiblePanel } from '@dafcoe/vue-collapsible-panel';
import '@dafcoe/vue-collapsible-panel/dist/vue-collapsible-panel.css';
import '@hennge/vue3-pagination/dist/vue3-pagination.css';
import MapChart from 'vue-chart-map';

const app = createApp(App);
app.use(router);
app.use(SmartTable);
app.use(LitepieDatepicker);
app.use(store);
app.use(VueAxios, axios);
app.use(VueSidebarMenu);
app.use(VueCollapsiblePanelGroup, VueCollapsiblePanel);
app.use(MapChart);
app.mount('#app');
globalComponents(app);
