import { App } from 'vue';
import VInput from '@/components/V/VInput/VInput.vue';
import VInputall from '@/components/V/VInputall/VInputall.vue';
import VButton from '@/components/V/VButton/VButton.vue';
import VLeftMenu from '@/components/V/VLeftMenu/VLeftMenu.vue';
// import VRightMenu from '@/components/V/VRightMenu/VRightMenu.vue'
import VLabel from '@/components/V/VLabel/VLabel.vue';
import VCheckbox from '@/components/V/VCheckbox/VCheckbox.vue';
import VPassword from '@/components/V/VPassword/VPassword.vue';
import Layout from '@/components/Layout/Layout.vue';
import VSmallButton from '@/components/V/VSmallButton/VSmallButton.vue';
import VTitle from '@/components/V/VTitle/VTitle.vue';
import VCardBox from '@/components/V/VCardBox/VCardBox.vue';
import VInputSearch from '@/components/V/VInputSearch/VInputSearch.vue';
import VProfile from '@/components/V/VProfile/VProfile.vue';
import VDatepicker from '@/components/V/VDatepicker/VDatepicker.vue';
import VBreadcrumb from '@/components/V/VBreadcrumb/VBreadcrumb.vue';
import VFilter from '@/components/V/VFilter/VFilter.vue';
import Vtoaster from '@/components/V/Vtoaster/Vtoaster.vue';
import VLoader from '@/components/V/VLoader/VLoader.vue';
import VConfirmationModal from '@/components/V/VConfirmationModal/VConfirmationModal.vue';
import VSelect from '@/components/V/VSelect/VSelect.vue';
import VNoData from '@/components/V/VNoData/VNoData.vue';
import VDetailLoader from '@/components/V/VDetailLoader/VDetailLoader.vue';
import VCardInnerBox from '@/components/V/VCardInnerBox/VCardInnerBox.vue';
import VTextarea from '@/components/V/VTextarea/VTextarea.vue';
import VFileUpload from '@/components/V/VFileUpload/VFileUpload.vue';
import VRadio from '@/components/V/VRadio/VRadio.vue';
import VNewpassword from '@/components/V/VNewpassword/VNewpassword.vue';
export const globalComponents = (app: App): void => {
  app.component('v-input', VInput);
  app.component('v-inputall', VInputall);
  app.component('v-button', VButton);
  app.component('v-left-menu', VLeftMenu);
  // app.component('V-right-menu', VRightMenu)
  app.component('v-label', VLabel);
  app.component('v-checkbox', VCheckbox);
  app.component('v-password', VPassword);
  app.component('layout', Layout);
  app.component('v-smallbutton', VSmallButton);
  app.component('v-title', VTitle);
  app.component('v-card-box', VCardBox);
  app.component('v-input-search', VInputSearch);
  app.component('v-profile', VProfile);
  app.component('v-date-picker', VDatepicker);
  app.component('v-breadcrumb', VBreadcrumb);
  app.component('v-filter', VFilter);
  app.component('v-toaster', Vtoaster);
  app.component('v-loader', VLoader);
  app.component('v-confirmation-modal', VConfirmationModal);
  app.component('v-select', VSelect);
  app.component('v-no-data', VNoData);
  app.component('v-eng-loader', VDetailLoader);
  app.component('v-card-inner-box', VCardInnerBox);
  app.component('v-textarea', VTextarea);
  app.component('v-file-upload', VFileUpload);
  app.component('v-radio', VRadio);
  app.component("v-newpassword", VNewpassword);
};
